site_name: BlendSQL
site_description: Unified dialect for orchestrating SQLite logic and LLM reasoning.

repo_name: parkervg/blendsql
repo_url: https://github.com/parkervg/blendsql

theme:
  name: material
  palette:
    - scheme: default
      primary: white
  logo: img/blender.png
  favicon: img/blender.png
  features:
    - content.code.copy
    - header.autohide
    - navigation.expand
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences



plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          docstring_options:
            ignore_init_summary: true
            merge_init_into_class: true
          options:
            show_submodules: true
            show_source: true
            docstring_style: google
            docstring_section_style: table
            show_docstring_examples: true
            show_symbol_type_heading: true
            show_if_no_docstring: False
  - search
  - section-index

nav:
  - Home:
    - Home: index.md
    - Examples from QA Datasets:
      - HybridQA: examples/hybridqa.md
      - OTT-QA: examples/ottqa.md
      - FEVEROUS: examples/feverous.md
    - FAQ: faq.md
  - Getting Started:
      - Quickstart: quickstart.md
  - Documentation:
      - Execute a BlendSQL Query: reference/execute-blendsql.md
      - Ingredients:
          - reference/ingredients/ingredients.md
          - Creating Custom Ingredients: reference/ingredients/creating-custom-ingredients.md
          - Built-in:
            - LLMMap: reference/ingredients/LLMMap.md
            - LLMQA: reference/ingredients/LLMQA.md
            - LLMJoin: reference/ingredients/LLMJoin.md
      - Blenders:
          - reference/blenders/blenders.md
          - OpenAI: reference/blenders/openai.md
          - Transformers: reference/blenders/transformers.md
      - Databases:
          - SQLite: reference/databases/sqlite.md
      - Technical Walkthrough: reference/technical_walkthrough.md
